# Generated by Django 5.1.4 on 2025-01-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productDesc', models.TextField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productImage', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
